/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
// RCC Registers (Reset and Clock Control)
#define RCC_BASE 0x44020C00
// Control Clock Gating to GPIO Ports
// Bit 1 Enables Clocking for GPIOB
// Bit 3 Enables Clocking for GPIOD
// Bit 4 Enables Clocking for GPIOE
// Bit 5 Enables Clocking for GPIOF
// Bit 6 Enables Clocking for GPIOG
#define RCC_AHB2ENR (*(volatile uint32_t*)(RCC_BASE + 0x8C))
// Control Clock Gating to High-Speed Peripheral Devices
// Bit 11 Enables Clocking for TIM1
#define RCC_APB2ENR (*(volatile uint32_t*)(RCC_BASE + 0xA4))
// Control Clock Gating to Low-Speed Peripheral Devices
// Bit 21 Enables Clocking for I2C1
#define RCC_APB1LENR (*(volatile uint32_t*)(RCC_BASE + 0x9C))

#define GPIOB_BASE 0x42020400
// Select the I/O Direction - Put in Alternate Function Mode: 10
#define GPIOB_MODER (*(volatile uint32_t*)(GPIOB_BASE + 0x00)) // GPIOB Address: 0x42020400 + Memory Offset: 0x00
// Select the I/O Output Type - Put in Open-Drain Mode: 1
#define GPIOB_OTYPER (*(volatile uint32_t*)(GPIOB_BASE + 0x04)) // GPIOB Address: 0x42020400 + Memory Offset: 0x04
// Select the I/O Pull-Up/Pull-Down Resistor Configuration - Put in Pull-Up Mode: 01
#define GPIOB_PUPDR (*(volatile uint32_t*)(GPIOB_BASE + 0x0C)) // GPIOB Address: 0x42020400 + Memory Offset: 0x0C
// Configure GPIOB Alternate Function Multiplexer Register High
#define GPIOB_AFRH (*(volatile uint32_t*)(GPIOB_BASE + 0x24)) // GPIOB Address: 0x42020400 + Memory Offset: 0x24

#define GPIOD_BASE 0x42020C00
// Select the I/O Direction Register - Put in Output Mode: 01
#define GPIOD_MODER (*(volatile uint32_t*)(GPIOD_BASE + 0x00)) // GPIOD Address: 0x42020C00 + Memory Offset: 0x00
// GPIO Port Output Data Register
#define GPIOD_ODR (*(volatile uint32_t*)(GPIOD_BASE + 0x14)) // GPIOD Address: 0x42020C00 + Memory Offset: 0x14

#define GPIOE_BASE 0x42021000
// Select the I/O Direction Register
#define GPIOE_MODER (*(volatile uint32_t*)(GPIOE_BASE + 0x00)) // GPIOE Address: 0x42021000 + Memory Offset: 0x00
// Select the I/O Pull-Up/Pull-Down Resistor Configuration
#define GPIOE_PUPDR (*(volatile uint32_t*)(GPIOE_BASE + 0x0C)) // GPIOE Address: 0x42021000 + Memory Offset: 0x0C
// GPIO Port Input Data Register
#define GPIOE_IDR (*(volatile uint32_t*)(GPIOE_BASE + 0x10)) // GPIOE Address: 0x42021000 + Memory Offset: 0x10
// GPIO Port Output Data Register
#define GPIOE_ODR (*(volatile uint32_t*)(GPIOE_BASE + 0x14)) // GPIOE Address: 0x42021000 + Memory Offset: 0x14
// Configure GPIOE Alternate Function Multiplexer Register High
#define GPIOE_AFRH (*(volatile uint32_t*)(GPIOE_BASE + 0x24)) // GPIOE Address: 0x42021000 + Memory Offset: 0x24

#define GPIOF_BASE 0x42021400
// Select the I/O Direction Register
#define GPIOF_MODER (*(volatile uint32_t*)(GPIOF_BASE + 0x00)) // GPIOF Address: 0x42021400 + Memory Offset: 0x00
// Select the I/O Pull-Up/Pull-Down Resistor Configuration
#define GPIOF_PUPDR (*(volatile uint32_t*)(GPIOF_BASE + 0x0C)) // GPIOF Address: 0x42021400 + Memory Offset: 0x0C
// GPIO Port Input Data Register
#define GPIOF_IDR (*(volatile uint32_t*)(GPIOF_BASE + 0x10)) // GPIOF Address: 0x42021400 + Memory Offset: 0x10
// GPIO Port Output Data Register
#define GPIOF_ODR (*(volatile uint32_t*)(GPIOF_BASE + 0x14)) // GPIOF Address: 0x42021400 + Memory Offset: 0x14

#define GPIOG_BASE 0x42021800
// Select the I/O Direction Register - Put in Output Mode: 01
#define GPIOG_MODER (*(volatile uint32_t*)(GPIOG_BASE + 0x00)) // GPIOG Address: 0x42021800 + Memory Offset: 0x00
// GPIO Port Output Data Register
#define GPIOG_ODR (*(volatile uint32_t*)(GPIOG_BASE + 0x14)) // GPIOG Address: 0x42021800 + Memory Offset: 0x14

#define TIM1_BASE 0x40012C00
// Control Register 1
#define TIM1_CR1 (*(volatile uint32_t*)(TIM1_BASE + 0x00)) // TIM1 Address: 0x40012C00 + Memory Offset: 0x00
// Capture/Compare Mode Register 1
#define TIM1_CCMR1 (*(volatile uint32_t*)(TIM1_BASE + 0x18)) // TIM1 Address: 0x40012C00 + Memory Offset: 0x18
// Capture/Compare Enable Register
#define TIM1_CCER (*(volatile uint32_t*)(TIM1_BASE + 0x20)) // TIM1 Address: 0x40012C00 + Memory Offset: 0x20
// Prescaler
#define TIM1_PSC (*(volatile uint32_t*)(TIM1_BASE + 0x28)) // TIM1 Address: 0x40012C00 + Memory Offset: 0x28
// Auto-Reload Register
#define TIM1_ARR (*(volatile uint32_t*)(TIM1_BASE + 0x2C)) // TIM1 Address: 0x40012C00 + Memory Offset: 0x2C
// Capture/Compare Register 1
#define TIM1_CCR1 (*(volatile uint32_t*)(TIM1_BASE + 0x34)) // TIM1 Address: 0x40012C00 + Memory Offset: 0x34
// Break and Dead-Time Register (Required for TIM1 Output)
#define TIM1_BDTR (*(volatile uint32_t*)(TIM1_BASE + 0x44)) // TIM1 Address: 0x40012C00 + Memory Offset: 0x44

#define I2C1_BASE 0x40005400
// Control Register 1
#define I2C1_CR1 (*(volatile uint32_t*)(I2C1_BASE + 0x00)) // I2C1 Address: 0x40005400 + Memory Offset: 0x00
// Control Register 2
#define I2C1_CR2 (*(volatile uint32_t*)(I2C1_BASE + 0x04)) // I2C1 Address: 0x40005400 + Memory Offset: 0x04
// Timing Register
#define I2C1_TIMINGR (*(volatile uint32_t*)(I2C1_BASE + 0x10)) // I2C1 Address: 0x40005400 + Memory Offset: 0x10
// Interrupt and Status Register
#define I2C1_ISR (*(volatile uint32_t*)(I2C1_BASE + 0x18)) // I2C1 Address: 0x40005400 + Memory Offset: 0x18
// Interrupt Clear Register
#define I2C1_ICR (*(volatile uint32_t*)(I2C1_BASE + 0x1C)) // I2C1 Address: 0x40005400 + Memory Offset: 0x1C
// Receive Data Register
#define I2C1_RXDR (*(volatile uint32_t*)(I2C1_BASE + 0x24)) // I2C1 Address: 0x40005400 + Memory Offset: 0x24
// Transmit Data Register
#define I2C1_TXDR (*(volatile uint32_t*)(I2C1_BASE + 0x28)) // I2C1 Address: 0x40005400 + Memory Offset: 0x28


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// generate delay using nested loops
void Delay(volatile uint32_t time) {
	// Controls overall delay length
    while(time--)
    {
        volatile uint32_t i;
        // Creates time-consuming instruction cycles
        for(i = 0; i < 4000; i++);
    }
}

// Frequencies for musical notes mapped to keypad options
const uint16_t TONE_FREQS[8] = {2093, 2349, 2637, 1976, 2960, 3136, 1760, 3951}; // 1 - C7 2 - D7 3 - E7 4 - B6 5 - F#7 6 - G7 7 - A6 8 - B7

// Maps keypad row/column positions to characters
char keypad_map[4][3] = {
    {'1','2','3'},
    {'4','5','6'},
    {'7','8','9'},
    {'*','0','#'}
};

// Scan keypad for pressed key
char keypad_getkey(void) {
    int row;
    // Scan each keypad row one at a time
    for(row = 0; row < 4; row++) {
    	// Set all row outputs HIGH
		GPIOF_ODR |= (1 << 7);
		GPIOF_ODR |= (1 << 8);
		GPIOE_ODR |= (1 << 3);
		GPIOE_ODR |= (1 << 6);

        // Drive current row LOW to isolate keys
    	switch(row)
    	{
    	    case 0:
    	        GPIOF_ODR &= ~(1 << 7); // Row 1 (PF7) driven LOW
    	        break;

    	    case 1:
    	        GPIOF_ODR &= ~(1 << 8); // Row 2 (PF8) driven LOW
    	        break;

    	    case 2:
    	        GPIOE_ODR &= ~(1 << 3); // Row 3 (PE3) driven LOW
    	        break;

    	    case 3:
    	        GPIOE_ODR &= ~(1 << 6); // Row 4 (PE6) driven LOW
    	        break;
    	}
        // Allow signals to stabilize
		Delay(1);

		// Check physical left column wire (PE5)
		if(!(GPIOE_IDR & (1 << 5))) {
			Delay(10); // Software debounce handling
			if (!(GPIOE_IDR & (1 << 5))) {
			    // Mapped to index 0 (Left Column: 1, 4, 7, *)
			    return keypad_map[row][0];
			}
		}
		// Check physical middle column wire (PE4)
		if(!(GPIOE_IDR & (1 << 4))) {
			Delay(10); // Software debounce handling
			if (!(GPIOE_IDR & (1 << 4))) {
			    // Mapped to index 1 (Middle Column: 2, 5, 8, 0)
			    return keypad_map[row][1];
			}
		}
		// Check physical right column wire (PE2)
		if(!(GPIOE_IDR & (1 << 2))) {
			Delay(10); // Software debounce handling
			if (!(GPIOE_IDR & (1 << 2))) {
			    // Mapped to index 2 (Right Column: 3, 6, 9, #)
			    return keypad_map[row][2];
			}
		}
	}
    // No key is detected
	return 0;
}

// Configures Timer Auto-Reload values to play specific buzzer frequencies
void playNote(uint16_t freq) {
	uint32_t arr;
	// Calculate target period ticks based on the timer clock settings
	arr = (400000 / freq) - 1;
	TIM1_ARR = arr; // Load calculated cycle limits into Auto-Reload Register
	TIM1_CCR1 = arr / 2; // Balance matching comparison duty cycle at a uniform 50%
}

// Writes a single byte of data to a specific 16-bit memory address inside the EEPROM
void EEPROM_WriteByte(uint16_t mem_address, uint8_t data) {
	// Clear any lingering error flags before starting transmission
	I2C1_ICR = 0xFFFFFFFF;
	// Setup: Slave Address 0x50, 3 Bytes to transmit, send START condition
	I2C1_CR2 = (0x50 << 1) | (3 << 16) | (1 << 13);
	// Write Address MSB
	while (!(I2C1_ISR & (1 << 1))); // Wait until TXIS flag is set
	I2C1_TXDR = (mem_address >> 8) & 0xFF;
	// Write Address LSB
	while (!(I2C1_ISR & (1 << 1))); // Wait until TXIS flag is set
	I2C1_TXDR = mem_address & 0xFF;
	// Write Data Byte
	while (!(I2C1_ISR & (1 << 1))); // Wait until TXIS flag is set
	I2C1_TXDR = data;
	// Wait for Transmission Complete (TC bit 6)
	while (!(I2C1_ISR & (1 << 6)));
	// Generate STOP Condition
	I2C1_CR2 |= (1 << 14);
	// Wait for the internal physical write processing layout cycle to clear
	Delay(25);
}

// Reads a single byte of data from a specific 16-bit memory address inside the EEPROM
uint8_t EEPROM_ReadByte(uint16_t mem_address) {
    uint8_t data = 0;
    // 1. Tell the EEPROM which internal address we want to read from (2 bytes address transfer)
    I2C1_CR2 = (0x50 << 1) | (2 << 16) | (1 << 13); // START write cycle
    while (!(I2C1_ISR & (1 << 1))); // Wait until TXIS flag is set
    I2C1_TXDR = (mem_address >> 8) & 0xFF;
    while (!(I2C1_ISR & (1 << 1))); // Wait until TXIS flag is set
    I2C1_TXDR = mem_address & 0xFF;
    while (!(I2C1_ISR & (1 << 6))); // Wait for transfer complete (TC bit 6)
    // 2. Restart the I2C bus in READ mode to receive 1 byte back from the EEPROM
    I2C1_CR2 = (0x50 << 1) | (1 << 16) | (1 << 10) | (1 << 13); // Set RD_WRN (bit 10) and START
    // 3. Wait until the data arrives in the Receive Data Register (RXNE bit)
    while (!(I2C1_ISR & (1 << 2)));
    data = I2C1_RXDR;
    // 4. Generate STOP condition
    I2C1_CR2 |= (1 << 14);
    return data;
}


int main(void)
{
	// Enable Peripherals Clocks
	RCC_AHB2ENR |= (1 << 1); // Enable Clock for GPIOB
	RCC_AHB2ENR |= (1 << 3); // Enable Clock for GPIOD
	RCC_AHB2ENR |= (1 << 4); // Enable Clock for GPIOE
	RCC_AHB2ENR |= (1 << 5); // Enable Clock for GPIOF
	RCC_AHB2ENR |= (1 << 6); // Enable Clock for GPIOG
	RCC_APB2ENR |= (1 << 11); // Enable Clock for TIM1
	RCC_APB1LENR |= (1 << 21); // Enable Clock for I2C1

	// Speaker Output
	// Configure Bits 19 & 18 for TIM1_CH1
	GPIOE_MODER &= ~(3 << (9 * 2)); // Clear PE9 Bits
	GPIOE_MODER |= (2 << (9 * 2)); // Set PE9 to Alternate Function Mode (MODER = 10)
	// Configure PE9 Alternate Function Multiplexer to AF1 (TIM1)
	// Pins 8-15 are in AFRH, PE9 is indexed at position (9 - 8) = 1 & Shift by 4 bits
	GPIOE_AFRH &= ~(0xF << (1 * 4)); // Clear current AF bits
	GPIOE_AFRH |=  (0x1 << (1 * 4)); // Set AF1 (0001)
	TIM1_PSC = 2000 - 1; // Scale Down Counter Speed Based on System Clock
	TIM1_ARR = 1000; // Duty Cycle Range Limits (0 to 1000)
	TIM1_CCR1 = 0; // Start Silent
	TIM1_CCMR1 &= ~(7 << 4); // Clear configuration bits for OC1M channel 1
	TIM1_CCMR1 |=  (6 << 4); // Set to PWM Mode 1 (Output high when counter < CCR1)
	TIM1_CCMR1 |= (1 << 3); // Enable Output Compare 1 Preload (OC1PE)
	TIM1_CCER |= (1 << 0); // Enable Channel 1 Output
	TIM1_BDTR |= (1 << 15); // Set Main Output Enable (MOE) Bit for Advanced Timers
	TIM1_CR1 |= (1 << 7); // Enable Auto-Reload Preload (ARPE)
	TIM1_CR1 |= (1 << 0); // Start Timer Counter

	// Keypad Output Pins
	GPIOF_MODER &= ~(3 << (7 * 2)); // Clear mode bits for PF7
	GPIOF_MODER |=  (1 << (7 * 2)); // Set PF7 as output (Keypad Row 1 - Pin 8)
	GPIOF_MODER &= ~(3 << (8 * 2)); // Clear mode bits for PF8
	GPIOF_MODER |=  (1 << (8 * 2)); // Set PF8 as output (Keypad Row 2 - Pin 7)
	GPIOE_MODER &= ~(3 << (3 * 2)); // Clear mode bits for PE3
	GPIOE_MODER |=  (1 << (3 * 2)); // Set PE3 as output (Keypad Row 3 - Pin 6)
	GPIOE_MODER &= ~(3 << (6 * 2)); // Clear mode bits for PE6
	GPIOE_MODER |=  (1 << (6 * 2)); // Set PE6 as output (Keypad Row 4 - Pin 5)
	GPIOE_MODER &= ~(3 << (5 * 2)); // Set PE5 as input (Keypad Col 1 - Pin 4)
	GPIOE_MODER &= ~(3 << (4 * 2)); // Set PE4 as input (Keypad Col 2 - Pin 3)
	GPIOE_MODER &= ~(3 << (2 * 2)); // Set PE2 as input (Keypad Col 3 - Pin 2)

	// Enable Pull-Up Resistors (Columns)
	GPIOE_PUPDR &= ~(3 << (5 * 2)); // Clear pull-up configuration for PE5
	GPIOE_PUPDR |=  (1 << (5 * 2)); // Pull-Up enabled on PE5
	GPIOE_PUPDR &= ~(3 << (4 * 2)); // Clear pull-up configuration for PE4
	GPIOE_PUPDR |=  (1 << (4 * 2)); // Pull-Up enabled on PE4
	GPIOE_PUPDR &= ~(3 << (2 * 2)); // Clear pull-up configuration for PE2
	GPIOE_PUPDR |=  (1 << (2 * 2)); // Pull-Up enabled on PE2

	// LED output pins
	// PD0 output (Playback Mode LED Indicator)
	GPIOD_MODER &= ~(3 << (0 * 2)); // Clear mode bits for PD0
	GPIOD_MODER |=  (1 << (0 * 2)); // Set PD0 as output (Playback Mode LED)
	// PD1 output (Record Mode LED Indicator)
	GPIOD_MODER &= ~(3 << (1 * 2)); // Clear mode bits for PD1
	GPIOD_MODER |=  (1 << (1 * 2)); // Set PD1 as output (Record Mode LED)
	// PG0 output (Play Mode LED Indicator)
	GPIOG_MODER &= ~(3 << (0 * 2)); // Clear mode bits for PG0
	GPIOG_MODER |=  (1 << (0 * 2)); // Set PG0 as output (Play Mode LED)

	// EEPROM I2C Physical Pin Configurations (SCL: PB8, SDA: PB9)
	GPIOB_MODER &= ~((3 << (8 * 2)) | (3 << (9 * 2))); // Clear bits
	GPIOB_MODER |=  ((2 << (8 * 2)) | (2 << (9 * 2))); // Set to Alternate Function Mode (10)
	GPIOB_OTYPER |= (1 << 8) | (1 << 9); // Configure Open-Drain Configuration
	GPIOB_PUPDR &= ~((3 << (8 * 2)) | (3 << (9 * 2))); // Clear Current Settings
	GPIOB_PUPDR |=  ((1 << (8 * 2)) | (1 << (9 * 2))); // Set PB8 and PB9 to Pull-Up (01)
	GPIOB_AFRH &= ~((0xF << (0 * 4)) | (0xF << (1 * 4))); // Clear current mappings
	GPIOB_AFRH |=  ((0x4 << (0 * 4)) | (0x4 << (1 * 4))); // Set both pins to AF4 (0100 - I2C1 Alternate Function)
	I2C1_TIMINGR = 0X10B07DB5; // Initialize I2C clock timing properties
	I2C1_CR1 |= (1 << 0); // Enable I2C peripheral hardware (PE bit)

	// Memory Mapping Configuration
	// Address 0x0000: Stored overall song size count
	// Address 0x0002+: Sequence stream data array blocks
	uint16_t rec_address = 2;
	uint16_t note_count = 0;

	// CRITICAL: Power-On Recovery Check
	// Retrieve the note count from the last active usage cycle before power down
	note_count = EEPROM_ReadByte(0x0000);
	if (note_count > 100 || note_count == 0xFF) {
		note_count = 0; // Uninitialized/corrupted flash state catch
	}

    enum {
    	PLAY_MODE,
		REC_MODE,
		PLAYBACK_MODE
    };

    char key;
    int currentMode;
	currentMode = PLAY_MODE;

	// Loop Forever
	for(;;) {
		key = keypad_getkey();
		if (key == 0) {
			TIM1_CCR1 = 0; // Mute sound output if no key is pressed
		}
		// Mode Selection
		// Active Selection: Play Mode
		if (key == '*') {
			GPIOD_ODR &= ~(1 << 0); // Turn OFF Playback LED
			GPIOD_ODR &= ~(1 << 1); // Turn OFF Record LED
			GPIOG_ODR |= (1 << 0); // Turn ON Play Mode LED
			currentMode = PLAY_MODE;
			while(keypad_getkey() == '*'); // Wait for button release
		}
		// Active Selection: Record Mode
		if (key == '0') {
			GPIOD_ODR &= ~(1 << 0); // Turn OFF Playback LED
			GPIOD_ODR |= (1 << 1); // Turn ON Record LED
			GPIOG_ODR &= ~(1 << 0); // Turn OFF Play Mode LED
			currentMode = REC_MODE;
			rec_address = 2;  // Reset address pointer on mode entry
			note_count = 0;   // Reset counter on mode entry
			EEPROM_WriteByte(0x0000, 0); // Clear saved count entry in hardware storage
			while(keypad_getkey() == '0'); // Wait for button release
		}
		// Active Selection: Playback Mode
		if (key == '#') {
			GPIOD_ODR |= (1 << 0); // Turn ON Playback LED
			GPIOD_ODR &= ~(1 << 1); // Turn OFF Record LED
			GPIOG_ODR &= ~(1 << 0); // Turn OFF Play Mode LED
			currentMode = PLAYBACK_MODE;
			while(keypad_getkey() == '#'); // Wait for button release
		}
		// Play Mode Execution
		if (currentMode == PLAY_MODE) {
			GPIOD_ODR &= ~(1 << 0); // Turn OFF Playback LED
			GPIOD_ODR &= ~(1 << 1); // Turn OFF Record LED
			GPIOG_ODR |= (1 << 0); // Turn ON Play Mode LED
			if (key >= '1' && key <= '8') {
				playNote(TONE_FREQS[key - '1']); // Run live scale sound configurations
			}
		}
		// Record Mode Execution
		if (currentMode == REC_MODE) {
			if (key >= '1' && key <= '8') {
				playNote(TONE_FREQS[key - '1']); // Emit audible verification note
				// 1. Write the key data to the current offset address
				EEPROM_WriteByte(rec_address, key);
				rec_address++;
				// 2. Increment our song size tracking variable
				if (note_count < 100) {
					note_count++;
				}
				// 3. Immediately save the updated count to address 0x0000
				EEPROM_WriteByte(0x0000, (uint8_t)note_count);
				// 4. Standby until user releases the mechanical button
				while (keypad_getkey() == key);
				TIM1_CCR1 = 0; // Cut tone output
			}
		}
		// Playback Mode Execution
		if (currentMode == PLAYBACK_MODE) {
			if (key == '9') {
				uint16_t play_address = 2; // Point stream cursor to the base song track
				uint16_t current_note = 0;
				// Cycle through the entire duration loop of the logged stream entries
				while (current_note < note_count) {
					uint8_t stored_key = EEPROM_ReadByte(play_address); // Query EEPROM
					if (stored_key >= '1' && stored_key <= '8') {
						playNote(TONE_FREQS[stored_key - '1']); // Output recorded notes
						Delay(1000); // Duration pace gate holding step
						TIM1_CCR1 = 0; // Short mute step between notes
						Delay(50);
					}
					play_address++;
					current_note++;
				}
				TIM1_CCR1 = 0; // Ensure timer silence upon execution loop closure
				while(keypad_getkey() == '9'); // Hold code block execution if button is flagged down
			}
		}
	}
}
